'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('Users', [
            {
                firstName: 'Allie',
                lastName: 'Ledster',
                gender: 'Female',
                address: '1 Porter Hill',
                birthday: '27/02/1965',
                phone: '5837725965',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk01@gmail.com',
            },
            {
                firstName: 'Tulley',
                lastName: 'Bythell',
                gender: 'Male',
                address: '94 Marcy Street',
                birthday: '01/10/2017',
                phone: '5327750368',
                address: '01 Nova Crossing',
                birthday: '05/06/1984',
                phone: '9405498090',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk02@gmail.com',
            },
            {
                firstName: 'Conchita',
                lastName: 'Frearson',
                gender: 'Female',
                address: '01180 Miller Hill',
                birthday: '10/06/1961',
                phone: '9808286236',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk03@gmail.com',
            },
            {
                firstName: 'Phoebe',
                lastName: 'Graysmark',
                gender: 'Female',
                address: '7 Ohio Plaza',
                birthday: '06/11/2016',
                phone: '7032920360',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk04@gmail.com',
            },
            {
                firstName: 'Fawnia',
                lastName: 'Hargroves',
                gender: 'Female',
                address: '58 Bluestem Point',
                birthday: '19/02/1977',
                phone: '8709294662',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk05@gmail.com',
            },
            {
                firstName: 'Krissy',
                lastName: 'Leahey',
                gender: 'Female',
                address: '2555 Blaine Terrace',
                birthday: '07/01/1958',
                phone: '7452407683',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk11@gmail.com',
            },
            {
                firstName: 'Emmanuel',
                lastName: 'Lunny',
                gender: 'Male',
                address: '9426 Fremont Street',
                birthday: '11/03/2019',
                phone: '8039573618',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk12@gmail.com',
            },
            {
                firstName: 'Felic',
                lastName: 'Turban',
                gender: 'Male',
                address: '91 Hovde Court',
                birthday: '08/04/1978',
                phone: '5783998381',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk13@gmail.com',
            },
            {
                firstName: 'Warren',
                lastName: 'Sporgeon',
                gender: 'Male',
                address: '050 Stang Drive',
                birthday: '27/06/1989',
                phone: '9076686585',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk14@gmail.com',
            },
            {
                firstName: 'Corey',
                lastName: 'Rowly',
                gender: 'Female',
                address: '59 John Wall Hill',
                birthday: '31/03/1963',
                phone: '5181787293',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk15@gmail.com',
            },
            {
                firstName: 'Nadean',
                lastName: 'Karpman',
                gender: 'Female',
                address: '6 Mifflin Lane',
                birthday: '24/12/1965',
                phone: '6454928825',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk21@gmail.com',
            },
            {
                firstName: 'Brett',
                lastName: 'Chimes',
                gender: 'Male',
                address: '571 Nobel Court',
                birthday: '06/10/2012',
                phone: '4891379441',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk22@gmail.com',
            },
            {
                firstName: 'Urbanus',
                lastName: 'Springle',
                gender: 'Male',
                address: '0117 1st Drive',
                birthday: '08/04/1943',
                phone: '1255999021',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk23@gmail.com',
            },
            {
                firstName: 'Artemus',
                lastName: 'Gerrie',
                gender: 'Male',
                address: '3174 Jana Parkway',
                birthday: '15/01/2013',
                phone: '2048985661',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk24@gmail.com',
            },
            {
                firstName: 'Sapphire',
                lastName: 'Pindar',
                gender: 'Female',
                address: '5 Corscot Hill',
                birthday: '15/02/2006',
                phone: '7861326713',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk25@gmail.com',
            },
            {
                firstName: 'Allie',
                lastName: 'Ledster',
                gender: 'Female',
                address: '1 Porter Hill',
                birthday: '27/02/1965',
                phone: '5837725965',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk01@gmail.com',
            },
            {
                firstName: 'Tulley',
                lastName: 'Bythell',
                gender: 'Male',
                address: '94 Marcy Street',
                birthday: '01/10/2017',
                phone: '5327750368',
                address: '01 Nova Crossing',
                birthday: '05/06/1984',
                phone: '9405498090',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk02@gmail.com',
            },
            {
                firstName: 'Conchita',
                lastName: 'Frearson',
                gender: 'Female',
                address: '01180 Miller Hill',
                birthday: '10/06/1961',
                phone: '9808286236',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk03@gmail.com',
            },
            {
                firstName: 'Phoebe',
                lastName: 'Graysmark',
                gender: 'Female',
                address: '7 Ohio Plaza',
                birthday: '06/11/2016',
                phone: '7032920360',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk04@gmail.com',
            },
            {
                firstName: 'Fawnia',
                lastName: 'Hargroves',
                gender: 'Female',
                address: '58 Bluestem Point',
                birthday: '19/02/1977',
                phone: '8709294662',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk05@gmail.com',
            },
            {
                firstName: 'Felic',
                lastName: 'Turban',
                gender: 'Male',
                address: '91 Hovde Court',
                birthday: '08/04/1978',
                phone: '5783998381',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk13@gmail.com',
            },
            {
                firstName: 'Warren',
                lastName: 'Sporgeon',
                gender: 'Male',
                address: '050 Stang Drive',
                birthday: '27/06/1989',
                phone: '9076686585',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk14@gmail.com',
            },

            {
                firstName: 'Brett',
                lastName: 'Chimes',
                gender: 'Male',
                address: '571 Nobel Court',
                birthday: '06/10/2012',
                phone: '4891379441',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk22@gmail.com',
            },
            {
                firstName: 'Urbanus',
                lastName: 'Springle',
                gender: 'Male',
                address: '0117 1st Drive',
                birthday: '08/04/1943',
                phone: '1255999021',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk23@gmail.com',
            },
            {
                firstName: 'Artemus',
                lastName: 'Gerrie',
                gender: 'Male',
                address: '3174 Jana Parkway',
                birthday: '15/01/2013',
                phone: '2048985661',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk24@gmail.com',
            },
            {
                firstName: 'Sapphire',
                lastName: 'Pindar',
                gender: 'Female',
                address: '5 Corscot Hill',
                birthday: '15/02/2006',
                phone: '7861326713',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk25@gmail.com',
            },
            {
                firstName: 'Tulley',
                lastName: 'Bythell',
                gender: 'Male',
                address: '94 Marcy Street',
                birthday: '01/10/2017',
                phone: '5327750368',
                address: '01 Nova Crossing',
                birthday: '05/06/1984',
                phone: '9405498090',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk02@gmail.com',
            },
            {
                firstName: 'Conchita',
                lastName: 'Frearson',
                gender: 'Female',
                address: '01180 Miller Hill',
                birthday: '10/06/1961',
                phone: '9808286236',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk03@gmail.com',
            },
            {
                firstName: 'Phoebe',
                lastName: 'Graysmark',
                gender: 'Female',
                address: '7 Ohio Plaza',
                birthday: '06/11/2016',
                phone: '7032920360',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk04@gmail.com',
            },
            {
                firstName: 'Fawnia',
                lastName: 'Hargroves',
                gender: 'Female',
                address: '58 Bluestem Point',
                birthday: '19/02/1977',
                phone: '8709294662',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk05@gmail.com',
            },
            {
                firstName: 'Krissy',
                lastName: 'Leahey',
                gender: 'Female',
                address: '2555 Blaine Terrace',
                birthday: '07/01/1958',
                phone: '7452407683',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk11@gmail.com',
            },
            {
                firstName: 'Emmanuel',
                lastName: 'Lunny',
                gender: 'Male',
                address: '9426 Fremont Street',
                birthday: '11/03/2019',
                phone: '8039573618',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk12@gmail.com',
            },
            {
                firstName: 'Felic',
                lastName: 'Turban',
                gender: 'Male',
                address: '91 Hovde Court',
                birthday: '08/04/1978',
                phone: '5783998381',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk13@gmail.com',
            },
            {
                firstName: 'Warren',
                lastName: 'Sporgeon',
                gender: 'Male',
                address: '050 Stang Drive',
                birthday: '27/06/1989',
                phone: '9076686585',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk14@gmail.com',
            },
            {
                firstName: 'Corey',
                lastName: 'Rowly',
                gender: 'Female',
                address: '59 John Wall Hill',
                birthday: '31/03/1963',
                phone: '5181787293',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk15@gmail.com',
            },
            {
                firstName: 'Nadean',
                lastName: 'Karpman',
                gender: 'Female',
                address: '6 Mifflin Lane',
                birthday: '24/12/1965',
                phone: '6454928825',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk21@gmail.com',
            },
            {
                firstName: 'Brett',
                lastName: 'Chimes',
                gender: 'Male',
                address: '571 Nobel Court',
                birthday: '06/10/2012',
                phone: '4891379441',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk22@gmail.com',
            },
            {
                firstName: 'Urbanus',
                lastName: 'Springle',
                gender: 'Male',
                address: '0117 1st Drive',
                birthday: '08/04/1943',
                phone: '1255999021',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk23@gmail.com',
            },
            {
                firstName: 'Artemus',
                lastName: 'Gerrie',
                gender: 'Male',
                address: '3174 Jana Parkway',
                birthday: '15/01/2013',
                phone: '2048985661',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk24@gmail.com',
            },
            {
                firstName: 'Sapphire',
                lastName: 'Pindar',
                gender: 'Female',
                address: '5 Corscot Hill',
                birthday: '15/02/2006',
                phone: '7861326713',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk25@gmail.com',
            },
            {
                firstName: 'Allie',
                lastName: 'Ledster',
                gender: 'Female',
                address: '1 Porter Hill',
                birthday: '27/02/1965',
                phone: '5837725965',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk01@gmail.com',
            },
            {
                firstName: 'Tulley',
                lastName: 'Bythell',
                gender: 'Male',
                address: '94 Marcy Street',
                birthday: '01/10/2017',
                phone: '5327750368',
                address: '01 Nova Crossing',
                birthday: '05/06/1984',
                phone: '9405498090',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk02@gmail.com',
            },
        ]);
    },

    down: async (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('Users', null, {});
    },
};
