'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('Users', [
            {
                firstName: 'Allie',
                lastName: 'Ledster',
                gender: 'Female',
                address: '1 Porter Hill',
                birthday: '27/02/1965',
                phone: '5837725965',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk01@gmail.com',
            },
            {
                firstName: 'Tulley',
                lastName: 'Bythell',
                gender: 'Male',
                address: '94 Marcy Street',
                birthday: '01/10/2017',
                phone: '5327750368',
                address: '01 Nova Crossing',
                birthday: '05/06/1984',
                phone: '9405498090',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk02@gmail.com',
            },
            {
                firstName: 'Conchita',
                lastName: 'Frearson',
                gender: 'Female',
                address: '01180 Miller Hill',
                birthday: '10/06/1961',
                phone: '9808286236',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk03@gmail.com',
            },
            {
                firstName: 'Phoebe',
                lastName: 'Graysmark',
                gender: 'Female',
                address: '7 Ohio Plaza',
                birthday: '06/11/2016',
                phone: '7032920360',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk04@gmail.com',
            },
            {
                firstName: 'Fawnia',
                lastName: 'Hargroves',
                gender: 'Female',
                address: '58 Bluestem Point',
                birthday: '19/02/1977',
                phone: '8709294662',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Admin',
                email: 'thanhminhspk05@gmail.com',
            },
            {
                firstName: 'Krissy',
                lastName: 'Leahey',
                gender: 'Female',
                address: '2555 Blaine Terrace',
                birthday: '07/01/1958',
                phone: '7452407683',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk11@gmail.com',
            },
            {
                firstName: 'Emmanuel',
                lastName: 'Lunny',
                gender: 'Male',
                address: '9426 Fremont Street',
                birthday: '11/03/2019',
                phone: '8039573618',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk12@gmail.com',
            },
            {
                firstName: 'Felic',
                lastName: 'Turban',
                gender: 'Male',
                address: '91 Hovde Court',
                birthday: '08/04/1978',
                phone: '5783998381',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk13@gmail.com',
            },
            {
                firstName: 'Warren',
                lastName: 'Sporgeon',
                gender: 'Male',
                address: '050 Stang Drive',
                birthday: '27/06/1989',
                phone: '9076686585',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk14@gmail.com',
            },
            {
                firstName: 'Corey',
                lastName: 'Rowly',
                gender: 'Female',
                address: '59 John Wall Hill',
                birthday: '31/03/1963',
                phone: '5181787293',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Doctor',
                email: 'thanhminhspk15@gmail.com',
            },
            {
                firstName: 'Nadean',
                lastName: 'Karpman',
                gender: 'Female',
                address: '6 Mifflin Lane',
                birthday: '24/12/1965',
                phone: '6454928825',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk21@gmail.com',
            },
            {
                firstName: 'Brett',
                lastName: 'Chimes',
                gender: 'Male',
                address: '571 Nobel Court',
                birthday: '06/10/2012',
                phone: '4891379441',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk22@gmail.com',
            },
            {
                firstName: 'Urbanus',
                lastName: 'Springle',
                gender: 'Male',
                address: '0117 1st Drive',
                birthday: '08/04/1943',
                phone: '1255999021',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk23@gmail.com',
            },
            {
                firstName: 'Artemus',
                lastName: 'Gerrie',
                gender: 'Male',
                address: '3174 Jana Parkway',
                birthday: '15/01/2013',
                phone: '2048985661',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk24@gmail.com',
            },
            {
                firstName: 'Sapphire',
                lastName: 'Pindar',
                gender: 'Female',
                address: '5 Corscot Hill',
                birthday: '15/02/2006',
                phone: '7861326713',
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                roleId: 'Patient',
                email: 'thanhminhspk25@gmail.com',
            },

            // FAKE DATA

            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Brenn',
                lastName: 'Haggish',
                email: 'bhaggish0@paypal.com',
                gender: 'Female',
                address: '72 Hovde Plaza',
                phone: '351 529 9344',
                birthday: '31/10/1961',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Ethe',
                lastName: 'Basketter',
                email: 'ebasketter1@tamu.edu',
                gender: 'Male',
                address: '2 1st Alley',
                phone: '972 868 5831',
                birthday: '01/07/1985',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Osmond',
                lastName: 'Callicott',
                email: 'ocallicott2@parallels.com',
                gender: 'Male',
                address: '2501 Grim Junction',
                phone: '782 296 6103',
                birthday: '14/07/1986',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Thane',
                lastName: "O'Cosgra",
                email: 'tocosgra3@bravesites.com',
                gender: 'Male',
                address: '02389 Ohio Parkway',
                phone: '999 680 5860',
                birthday: '27/02/2014',
                roleId: 'Admin',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Berni',
                lastName: 'Seagar',
                email: 'bseagar4@omniture.com',
                gender: 'Female',
                address: '993 Marquette Court',
                phone: '694 895 9693',
                birthday: '26/07/1961',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Lind',
                lastName: 'Korn',
                email: 'lkorn5@exblog.jp',
                gender: 'Male',
                address: '3110 John Wall Street',
                phone: '536 145 2357',
                birthday: '21/12/1976',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Van',
                lastName: 'Dionisetto',
                email: 'vdionisetto6@last.fm',
                gender: 'Male',
                address: '46 Linden Plaza',
                phone: '207 944 6956',
                birthday: '18/07/2020',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Brynn',
                lastName: 'Gerriessen',
                email: 'bgerriessen7@ocn.ne.jp',
                gender: 'Female',
                address: '439 Armistice Pass',
                phone: '467 592 2124',
                birthday: '15/06/1989',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Darby',
                lastName: 'Bales',
                email: 'dbales8@geocities.com',
                gender: 'Female',
                address: '480 American Center',
                phone: '552 753 1879',
                birthday: '29/01/1968',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Ruy',
                lastName: 'Carbine',
                email: 'rcarbine9@instagram.com',
                gender: 'Male',
                address: '23 Duke Plaza',
                phone: '423 851 5286',
                birthday: '25/08/2002',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Berke',
                lastName: 'Triggle',
                email: 'btrigglea@odnoklassniki.ru',
                gender: 'Male',
                address: '825 Starling Park',
                phone: '147 972 5856',
                birthday: '24/09/1991',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Philly',
                lastName: 'Woodsford',
                email: 'pwoodsfordb@marketwatch.com',
                gender: 'Male',
                address: '804 Jenna Plaza',
                phone: '783 731 5039',
                birthday: '22/01/1985',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Cordell',
                lastName: 'Rhelton',
                email: 'crheltonc@simplemachines.org',
                gender: 'Female',
                address: '3046 Delladonna Center',
                phone: '540 413 0378',
                birthday: '20/07/2013',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Meagan',
                lastName: 'Mungin',
                email: 'mmungind@icq.com',
                gender: 'Female',
                address: '317 Onsgard Point',
                phone: '370 181 7554',
                birthday: '18/12/2001',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Alic',
                lastName: 'Kynforth',
                email: 'akynforthe@soup.io',
                gender: 'Female',
                address: '3619 Michigan Center',
                phone: '973 729 8012',
                birthday: '09/06/1965',
                roleId: 'Admin',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Gina',
                lastName: 'Sutter',
                email: 'gsutterf@nih.gov',
                gender: 'Female',
                address: '1931 Loomis Plaza',
                phone: '481 360 1385',
                birthday: '22/02/1978',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Ariel',
                lastName: 'MacDearmid',
                email: 'amacdearmidg@ifeng.com',
                gender: 'Female',
                address: '80 Springview Drive',
                phone: '613 174 0666',
                birthday: '18/02/1952',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Darci',
                lastName: 'Wilhelmy',
                email: 'dwilhelmyh@pagesperso-orange.fr',
                gender: 'Female',
                address: '08887 Marcy Alley',
                phone: '497 341 5169',
                birthday: '08/06/1998',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Thibaut',
                lastName: 'Shrimpling',
                email: 'tshrimplingi@redcross.org',
                gender: 'Male',
                address: '687 Raven Place',
                phone: '837 428 3306',
                birthday: '03/02/2008',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Cathryn',
                lastName: 'Pauer',
                email: 'cpauerj@imageshack.us',
                gender: 'Male',
                address: '6709 High Crossing Point',
                phone: '900 117 4552',
                birthday: '27/12/1986',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Martguerita',
                lastName: 'Askie',
                email: 'maskiek@geocities.jp',
                gender: 'Male',
                address: '059 Golf Avenue',
                phone: '960 977 3329',
                birthday: '09/07/1980',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Joanna',
                lastName: 'Challes',
                email: 'jchallesl@diigo.com',
                gender: 'Male',
                address: '280 Memorial Way',
                phone: '824 297 6195',
                birthday: '10/11/1976',
                roleId: 'Male',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Olly',
                lastName: 'Mixter',
                email: 'omixterm@cnet.com',
                gender: 'Male',
                address: '147 Arrowood Crossing',
                phone: '142 542 5718',
                birthday: '27/12/2001',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Kerby',
                lastName: 'Wessing',
                email: 'kwessingn@marriott.com',
                gender: 'Male',
                address: '5955 Kropf Lane',
                phone: '638 513 7133',
                birthday: '25/01/1977',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Jan',
                lastName: 'Seabright',
                email: 'jseabrighto@tinypic.com',
                gender: 'Female',
                address: '7136 Alpine Street',
                phone: '249 517 2303',
                birthday: '26/11/1973',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Abdel',
                lastName: 'Wallbrook',
                email: 'awallbrookp@hp.com',
                gender: 'Female',
                address: '8056 Bellgrove Crossing',
                phone: '797 864 9600',
                birthday: '25/12/2021',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Bertrando',
                lastName: 'Beecheno',
                email: 'bbeechenoq@usatoday.com',
                gender: 'Male',
                address: '987 Arapahoe Point',
                phone: '610 198 8983',
                birthday: '29/07/1971',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Yelena',
                lastName: 'Hawkins',
                email: 'yhawkinsr@telegraph.co.uk',
                gender: 'Female',
                address: '5891 Cardinal Plaza',
                phone: '234 320 3041',
                birthday: '30/12/2022',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Allan',
                lastName: 'Neubigin',
                email: 'aneubigins@gmpg.org',
                gender: 'Female',
                address: '825 Raven Avenue',
                phone: '180 888 3056',
                birthday: '04/11/2012',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Timothea',
                lastName: 'de Aguirre',
                email: 'tdeaguirret@senate.gov',
                gender: 'Female',
                address: '52 Golf Crossing',
                phone: '570 665 8362',
                birthday: '23/12/1982',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Arluene',
                lastName: 'Goscar',
                email: 'agoscaru@geocities.jp',
                gender: 'Female',
                address: '270 Doe Crossing Park',
                phone: '699 820 8652',
                birthday: '20/10/1978',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Kelbee',
                lastName: 'Aked',
                email: 'kakedv@bizjournals.com',
                gender: 'Female',
                address: '4119 Waxwing Plaza',
                phone: '555 841 5145',
                birthday: '17/04/1951',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Patty',
                lastName: 'Birtles',
                email: 'pbirtlesw@mtv.com',
                gender: 'Male',
                address: '175 Village Way',
                phone: '390 437 1248',
                birthday: '04/04/1950',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Gail',
                lastName: 'Manston',
                email: 'gmanstonx@google.ca',
                gender: 'Male',
                address: '17441 Emmet Road',
                phone: '720 899 7513',
                birthday: '05/02/2018',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Alverta',
                lastName: 'Stiell',
                email: 'astielly@bigcartel.com',
                gender: 'Male',
                address: '4782 Messerschmidt Court',
                phone: '600 216 2284',
                birthday: '10/01/2020',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Fabian',
                lastName: 'Tootell',
                email: 'ftootellz@wikispaces.com',
                gender: 'Male',
                address: '936 Holmberg Plaza',
                phone: '767 459 4542',
                birthday: '15/10/2013',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Archaimbaud',
                lastName: 'De Gregoli',
                email: 'adegregoli10@abc.net.au',
                gender: 'Female',
                address: '8737 Kedzie Court',
                phone: '187 462 5134',
                birthday: '09/01/1977',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Clarice',
                lastName: 'Hawkswood',
                email: 'chawkswood11@shareasale.com',
                gender: 'Male',
                address: '636 Melvin Plaza',
                phone: '101 895 3099',
                birthday: '26/10/1983',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Genni',
                lastName: 'Lewisham',
                email: 'glewisham12@google.co.uk',
                gender: 'Female',
                address: '8 Fulton Road',
                phone: '307 321 6013',
                birthday: '11/06/1973',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Randi',
                lastName: 'Archibould',
                email: 'rarchibould13@time.com',
                gender: 'Female',
                address: '604 Fordem Crossing',
                phone: '272 482 7652',
                birthday: '09/04/1994',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Mathian',
                lastName: 'Pook',
                email: 'mpook14@prlog.org',
                gender: 'Female',
                address: '412 Brickson Park Place',
                phone: '971 766 7829',
                birthday: '17/01/1962',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Frayda',
                lastName: 'Dumpleton',
                email: 'fdumpleton15@mashable.com',
                gender: 'Male',
                address: '62 Northland Place',
                phone: '827 542 7652',
                birthday: '06/08/2016',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Thaddeus',
                lastName: 'Heningam',
                email: 'theningam16@vinaora.com',
                gender: 'Female',
                address: '94 Bellgrove Way',
                phone: '261 738 7411',
                birthday: '20/11/1986',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Evelyn',
                lastName: 'Binns',
                email: 'ebinns17@google.fr',
                gender: 'Male',
                address: '75316 Thierer Road',
                phone: '659 749 2315',
                birthday: '09/10/1950',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Thebault',
                lastName: 'Chaloner',
                email: 'tchaloner18@walmart.com',
                gender: 'Female',
                address: '14 Nelson Circle',
                phone: '508 447 6162',
                birthday: '24/07/1956',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Rikki',
                lastName: 'Kirkbright',
                email: 'rkirkbright19@gnu.org',
                gender: 'Male',
                address: '3026 Merchant Court',
                phone: '840 674 5692',
                birthday: '12/09/1995',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Josias',
                lastName: 'Kidby',
                email: 'jkidby1a@mayoclinic.com',
                gender: 'Male',
                address: '9 Ruskin Junction',
                phone: '406 694 9155',
                birthday: '29/12/1985',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Johnny',
                lastName: 'Elce',
                email: 'jelce1b@cocolog-nifty.com',
                gender: 'Female',
                address: '003 New Castle Trail',
                phone: '515 436 9575',
                birthday: '13/10/1959',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Alvin',
                lastName: 'Dowdney',
                email: 'adowdney1c@nyu.edu',
                gender: 'Male',
                address: '392 Rusk Center',
                phone: '642 905 4670',
                birthday: '04/08/1974',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Pamela',
                lastName: 'Arnfield',
                email: 'parnfield1d@oakley.com',
                gender: 'Male',
                address: '42 Starling Drive',
                phone: '511 590 5230',
                birthday: '01/11/1973',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Lissie',
                lastName: 'Pibsworth',
                email: 'lpibsworth1e@facebook.com',
                gender: 'Female',
                address: '350 Mayfield Terrace',
                phone: '945 100 5539',
                birthday: '21/05/1996',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Matty',
                lastName: 'Latchford',
                email: 'mlatchford1f@cloudflare.com',
                gender: 'Female',
                address: '30 Erie Parkway',
                phone: '450 439 6894',
                birthday: '27/10/1999',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Gary',
                lastName: 'Cornu',
                email: 'gcornu1g@google.com.hk',
                gender: 'Male',
                address: '9089 Transport Way',
                phone: '257 296 2416',
                birthday: '01/08/2007',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Billy',
                lastName: 'Cavil',
                email: 'bcavil1h@weather.com',
                gender: 'Male',
                address: '75072 Jackson Drive',
                phone: '463 222 1604',
                birthday: '28/02/2005',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Fern',
                lastName: 'Elliston',
                email: 'felliston1i@list-manage.com',
                gender: 'Female',
                address: '6306 Memorial Avenue',
                phone: '596 107 1992',
                birthday: '05/10/1996',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Darlene',
                lastName: 'Obert',
                email: 'dobert1j@adobe.com',
                gender: 'Male',
                address: '92 Victoria Plaza',
                phone: '398 814 2004',
                birthday: '23/05/1990',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Georgeanne',
                lastName: "O'Neary",
                email: 'goneary1k@blogs.com',
                gender: 'Female',
                address: '624 East Center',
                phone: '101 683 8555',
                birthday: '13/09/1988',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Casie',
                lastName: 'Meriott',
                email: 'cmeriott1l@constantcontact.com',
                gender: 'Male',
                address: '84324 Service Pass',
                phone: '831 705 6993',
                birthday: '12/11/2005',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Penn',
                lastName: 'Thorp',
                email: 'pthorp1m@shop-pro.jp',
                gender: 'Female',
                address: '1043 Victoria Hill',
                phone: '431 885 4755',
                birthday: '09/12/2007',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Bernice',
                lastName: 'Orum',
                email: 'borum1n@tamu.edu',
                gender: 'Male',
                address: '77431 Novick Terrace',
                phone: '987 352 5388',
                birthday: '27/06/1966',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Maiga',
                lastName: 'Mc Curlye',
                email: 'mmccurlye1o@japanpost.jp',
                gender: 'Female',
                address: '7 Kropf Alley',
                phone: '451 513 5457',
                birthday: '20/04/2001',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Alastair',
                lastName: 'Ellesworth',
                email: 'aellesworth1p@homestead.com',
                gender: 'Female',
                address: '84985 Amoth Way',
                phone: '199 423 9543',
                birthday: '25/03/2005',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Kari',
                lastName: 'Josupeit',
                email: 'kjosupeit1q@ucla.edu',
                gender: 'Female',
                address: '927 Buell Hill',
                phone: '880 695 4159',
                birthday: '08/10/2015',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Minette',
                lastName: 'Ruller',
                email: 'mruller1r@yelp.com',
                gender: 'Female',
                address: '4 Doe Crossing Hill',
                phone: '825 663 6046',
                birthday: '03/03/2020',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Godfry',
                lastName: 'Stannering',
                email: 'gstannering1s@desdev.cn',
                gender: 'Male',
                address: '2 Iowa Plaza',
                phone: '195 824 5592',
                birthday: '03/01/1971',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Bradley',
                lastName: 'Kuller',
                email: 'bkuller1t@sourceforge.net',
                gender: 'Male',
                address: '9394 Vahlen Center',
                phone: '789 931 8507',
                birthday: '16/11/1991',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Sigvard',
                lastName: 'Kasman',
                email: 'skasman1u@trellian.com',
                gender: 'Female',
                address: '069 Roth Pass',
                phone: '128 125 2434',
                birthday: '20/11/1991',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Helaine',
                lastName: 'Pischoff',
                email: 'hpischoff1v@cloudflare.com',
                gender: 'Male',
                address: '7 Warrior Parkway',
                phone: '304 326 0470',
                birthday: '20/07/1982',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Trever',
                lastName: 'Cracknall',
                email: 'tcracknall1w@msn.com',
                gender: 'Female',
                address: '736 Ridge Oak Terrace',
                phone: '989 481 3884',
                birthday: '01/09/1982',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Tani',
                lastName: 'Andover',
                email: 'tandover1x@hud.gov',
                gender: 'Male',
                address: '46808 Clove Trail',
                phone: '426 230 5376',
                birthday: '19/11/2018',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Izabel',
                lastName: 'Stather',
                email: 'istather1y@sakura.ne.jp',
                gender: 'Male',
                address: '0 Anderson Place',
                phone: '601 547 9805',
                birthday: '08/01/1962',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Roosevelt',
                lastName: 'Cordon',
                email: 'rcordon1z@wiley.com',
                gender: 'Female',
                address: '4446 Manitowish Park',
                phone: '101 680 1860',
                birthday: '20/06/1999',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Page',
                lastName: 'Cokly',
                email: 'pcokly20@github.io',
                gender: 'Male',
                address: '20 Acker Trail',
                phone: '288 496 3047',
                birthday: '17/07/1970',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Fred',
                lastName: 'Roscow',
                email: 'froscow21@list-manage.com',
                gender: 'Male',
                address: '5580 Green Parkway',
                phone: '133 390 9823',
                birthday: '06/12/1960',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Bethena',
                lastName: 'Skottle',
                email: 'bskottle22@psu.edu',
                gender: 'Male',
                address: '911 Stuart Avenue',
                phone: '130 483 6044',
                birthday: '08/09/1977',
                roleId: 'Admin',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Clyve',
                lastName: 'Clementi',
                email: 'cclementi23@uiuc.edu',
                gender: 'Male',
                address: '456 Hagan Crossing',
                phone: '972 473 9649',
                birthday: '06/01/1974',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Isabella',
                lastName: 'Bushrod',
                email: 'ibushrod24@last.fm',
                gender: 'Female',
                address: '2846 Graedel Way',
                phone: '862 816 5598',
                birthday: '17/06/2016',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Phineas',
                lastName: 'Gammons',
                email: 'pgammons25@mlb.com',
                gender: 'Female',
                address: '3 Glendale Point',
                phone: '512 994 3048',
                birthday: '17/02/1983',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Freedman',
                lastName: 'German',
                email: 'fgerman26@dot.gov',
                gender: 'Male',
                address: '61 Schmedeman Terrace',
                phone: '972 808 1365',
                birthday: '07/08/1984',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Kristel',
                lastName: 'Brewitt',
                email: 'kbrewitt27@opera.com',
                gender: 'Male',
                address: '0 Golf Parkway',
                phone: '846 319 9125',
                birthday: '12/06/1969',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Jenny',
                lastName: 'Boik',
                email: 'jboik28@gov.uk',
                gender: 'Female',
                address: '00300 Buell Pass',
                phone: '236 676 8351',
                birthday: '20/09/1991',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Lucais',
                lastName: 'McKenney',
                email: 'lmckenney29@360.cn',
                gender: 'Male',
                address: '952 Walton Lane',
                phone: '924 544 7305',
                birthday: '12/02/1965',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Doralia',
                lastName: 'Cottis',
                email: 'dcottis2a@cmu.edu',
                gender: 'Male',
                address: '2390 Michigan Parkway',
                phone: '604 225 1515',
                birthday: '08/03/2018',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Danit',
                lastName: 'Headland',
                email: 'dheadland2b@ucla.edu',
                gender: 'Female',
                address: '96977 Blaine Terrace',
                phone: '155 520 8485',
                birthday: '02/08/2008',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Adeline',
                lastName: 'Kohrsen',
                email: 'akohrsen2c@irs.gov',
                gender: 'Male',
                address: '6 David Center',
                phone: '969 370 2316',
                birthday: '21/10/1977',
                roleId: 'Male',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Jereme',
                lastName: 'Viste',
                email: 'jviste2d@washingtonpost.com',
                gender: 'Female',
                address: '4486 Memorial Point',
                phone: '840 968 9104',
                birthday: '28/04/1955',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Haze',
                lastName: 'Weddeburn',
                email: 'hweddeburn2e@t-online.de',
                gender: 'Female',
                address: '3 Del Sol Road',
                phone: '133 128 8496',
                birthday: '30/12/1989',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Loretta',
                lastName: 'Morch',
                email: 'lmorch2f@weebly.com',
                gender: 'Female',
                address: '2 Bluestem Parkway',
                phone: '277 205 0733',
                birthday: '21/01/1962',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Jilleen',
                lastName: 'Blowin',
                email: 'jblowin2g@over-blog.com',
                gender: 'Male',
                address: '7 Longview Crossing',
                phone: '139 512 5368',
                birthday: '07/11/1951',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Jozef',
                lastName: 'Eymor',
                email: 'jeymor2h@virginia.edu',
                gender: 'Male',
                address: '4 Corben Street',
                phone: '145 450 8850',
                birthday: '06/08/1978',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Rycca',
                lastName: 'Thorald',
                email: 'rthorald2i@apache.org',
                gender: 'Female',
                address: '466 Moose Trail',
                phone: '692 640 4422',
                birthday: '06/08/2021',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Adaline',
                lastName: 'Buyers',
                email: 'abuyers2j@fastcompany.com',
                gender: 'Female',
                address: '42 3rd Parkway',
                phone: '771 137 4801',
                birthday: '23/06/1998',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Kathlin',
                lastName: 'Carwithim',
                email: 'kcarwithim2k@bandcamp.com',
                gender: 'Male',
                address: '4473 Clarendon Terrace',
                phone: '445 346 6464',
                birthday: '20/04/1971',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Leroy',
                lastName: 'McGlone',
                email: 'lmcglone2l@cocolog-nifty.com',
                gender: 'Female',
                address: '850 Harbort Avenue',
                phone: '395 134 8691',
                birthday: '03/10/1956',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Marcellus',
                lastName: 'Ivashin',
                email: 'mivashin2m@wix.com',
                gender: 'Female',
                address: '116 Russell Circle',
                phone: '451 991 3836',
                birthday: '29/01/2005',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Roda',
                lastName: 'Bowller',
                email: 'rbowller2n@walmart.com',
                gender: 'Male',
                address: '175 Browning Hill',
                phone: '119 374 1216',
                birthday: '10/08/1961',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Neysa',
                lastName: 'Swine',
                email: 'nswine2o@flavors.me',
                gender: 'Female',
                address: '38 Stephen Drive',
                phone: '778 442 1908',
                birthday: '20/09/2017',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Lurette',
                lastName: 'Caveney',
                email: 'lcaveney2p@jalbum.net',
                gender: 'Male',
                address: '429 Mayer Parkway',
                phone: '922 986 4337',
                birthday: '04/08/1990',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Elisha',
                lastName: 'McLardie',
                email: 'emclardie2q@cdc.gov',
                gender: 'Male',
                address: '09 Riverside Avenue',
                phone: '370 868 6772',
                birthday: '22/11/1961',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Gib',
                lastName: 'Ewence',
                email: 'gewence2r@so-net.ne.jp',
                gender: 'Male',
                address: '3479 Northridge Way',
                phone: '394 890 6729',
                birthday: '14/01/1988',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Irma',
                lastName: 'Alvy',
                email: 'ialvy2s@sciencedaily.com',
                gender: 'Female',
                address: '49 Ridgeview Lane',
                phone: '739 189 6666',
                birthday: '31/12/1991',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Horten',
                lastName: 'Malyon',
                email: 'hmalyon2t@marriott.com',
                gender: 'Female',
                address: '798 Lotheville Terrace',
                phone: '201 435 9230',
                birthday: '14/02/1975',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Bobette',
                lastName: "O'Fogarty",
                email: 'bofogarty2u@slate.com',
                gender: 'Male',
                address: '7682 Comanche Parkway',
                phone: '717 974 5998',
                birthday: '09/07/2009',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Wolf',
                lastName: 'Pestridge',
                email: 'wpestridge2v@smh.com.au',
                gender: 'Male',
                address: '47992 Sugar Avenue',
                phone: '925 111 0767',
                birthday: '16/09/1981',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Northrup',
                lastName: 'Perrelli',
                email: 'nperrelli2w@uiuc.edu',
                gender: 'Female',
                address: '4865 Vernon Street',
                phone: '523 855 2647',
                birthday: '01/01/2002',
                roleId: 'Patient',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Josee',
                lastName: 'Angood',
                email: 'jangood2x@zimbio.com',
                gender: 'Female',
                address: '2 Talmadge Hill',
                phone: '162 459 4559',
                birthday: '25/07/1989',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Jackquelin',
                lastName: 'Berford',
                email: 'jberford2y@sfgate.com',
                gender: 'Male',
                address: '8346 3rd Street',
                phone: '923 503 3104',
                birthday: '30/05/2013',
                roleId: 'Doctor',
            },
            {
                password: '$2a$10$VZE2sBB.Q9KgwHTdDP8niukBE4RDwQAOy0OJYW.a1ctlRzAowxBxW',
                firstName: 'Maxi',
                lastName: 'Szymoni',
                email: 'mszymoni2z@nasa.gov',
                gender: 'Male',
                address: '7511 Magdeline Pass',
                phone: '216 580 1621',
                birthday: '06/09/1968',
                roleId: 'Doctor',
            },
        ]);
    },

    down: async (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('Users', null, {});
    },
};
